matrix:
  include:
    - os: linux
      sudo: false
    # - os: osx
    #   osx_image: xcode7.3

language: node_js

node_js:
  - '0.12'
  - '4'
  - '5'

# before install:
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install node; fi
